# Generated by Django 4.2.7 on 2023-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='debt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
