# Generated by Django 4.2.7 on 2023-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodokanal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(default=996700809098, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirement1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirement2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirement3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
