# Generated by Django 4.2.7 on 2023-11-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vodokanal', '0005_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Gallery',
        ),
    ]
