# Generated by Django 4.2.7 on 2023-11-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vodokanal', '0006_rename_photo_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
